### ISSUE TITLE
React Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ayjayem** [usergeek/usergeek-ic-js#2]
Hi there!

Usergeek analytics look great - was able to get set up locally with no issues; but in production, I get the error in the title. From what I've been able to glean from the console error, the source of the issue may be in constants.js in the canisters directory.. but haven't been able to resolve. I wonder if anyone else has mentioned this issue?

**Comment by alexeychirkov** [comment]
@ayjayem Hey!

InternetComputer (Dfinity) related client libraries and projects use Node.js like variables (e.g. `process.env.VARIABLE`) internally.

Seems like you are using clean webpack v5 (it does no longer include a polyfill for this Node.js variable).

To use `process.env` variables please use `DefinePlugin` plugin in your webpack.config.js:

1. Install [`process`](https://www.npmjs.com/package/process) npm module 
2. Use `DefinePlugin`
```javascript
module.exports = {
     //...
     plugins: [
          //...
          new webpack.ProvidePlugin({
               process: require.resolve("process/browser"),
          })
          //...
     ],
     //...
}
```

**Comment by ayjayem** [comment]
Thanks Alexey!

I'm actually using Vite (I definitely should have shared more about my config in advance - apologies!) - but your answer inspired me to look at a Vite-specific solution (I thought it may have more to do with React, based on some initial Googling)... and was able to get something that works! For Vite, this worked for me:

```
export default defineConfig({
  ...
  define: {
    ...
    "process.env": {}  // NEW, for testing...
  },
})
```

Thanks for your prompt assistance!
